build: Update post-checkout to pull on main (#7)
When checking out main we often want to pull changes from remote, this
makes that behaviour built in.

diff --git a/.githooks/post-checkout b/.githooks/post-checkout
--- a/.githooks/post-checkout
+++ b/.githooks/post-checkout
@@ -4,5 +4,12 @@
 
 # $3 is 1 for branch checkout, 0 for file checkout
 if [ "$3" = "1" ]; then
+  # If we're checking out 'main' then run git pull
+  current_branch=$(git branch --show-current)
+  if [ "$current_branch" = "main" ]; then
+    echo "Switched to main. Pulling latest changes..."
+    git pull --quiet || echo "Warning: git pull failed, continuing with local version."
+  fi
   make install
 fi
+
